### ISSUE TITLE
Attempting to open/build

### ISSUE THREAD

**Issue by Casuallynoted** [Tcll5850/Universal-Game-Editor#1]
Hello there! I've been attempting to get UGE to open or build, I have the pyproj open in VS, but it says some files are missing, and while it exits with code 0, it doesn't produce any sort of .exe or .py for me to open like with UGC. I don't see any precompiled binaries either. In addition, the commands specified in the readme (from UGE import API and API.help(Object=None)) Don't appear to function correctly as it doesn't appear to import anything. Is there something I may be doing incorrectly?

**Comment by Tcll** [comment]
it's not finished yet, I'm still porting.

Also, you don't build with VS, or IDEA, or that...
The EXE that was included with UMC is nothing more than what's basically a BAT file, and was built with GameMaker8. (the icon replaced with ResourceHacker)

All it did was detect your CPU architecture and launch the appropriate interpreter with `./app/win/x##/python.exe loader.py 'x##'`.
(the command line here is changing to retrieve the CPU architecture internally from the included interpreter)

as for the missing files related to the pyproj, the whole thing needs to be rebuilt as it still follows UMC's structure...
I haven't been able to get VS working on my machine recently and haven't been able to fix it...
I may need to start over and build a new VM before I'll be able to fix that.

still, I currently wouldn't recommend working with this source just yet.
